### ISSUE TITLE
Maturity vector

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/gfiscam#1]
Model does not converge if maturity vector data is included as in the herring example

MAC Error message: Hessian error: Warning -- Hessian does not appear to be positive definite
PC Error message: Error in matrix inverse -- matrix singular in inv(dmatrix)

**Comment by cgrandin** [comment]
I can take a look if you add the files to the example folder - include the maturity vector

**Comment by cgrandin** [comment]
Here's what I've found so far. A lot of this is also for my own memory as I'm off until next week and will have to come back to it.

The problem lies in the calcReferencepoints() function, on the last line shown here:

Msy c_msy(d_ro,d_h,M_bar,d_rho,dWt_bar,fa_bar,&d_V);
fmsy(g) = 0.1;
**c_msy.get_fmsy(fmsy(g));**

I ran the debugger and found that in the **get_fmsy()** function in the msy.cpp file, there is a do..while loop which is the iterative newton-rhapson implementation for solving fe, the equilibrium fishing mortality. This makes it about 20 or so iterations, increasing until it suddenly goes hugely negative, causing the errors. Unfortunately this means debugging the **calcEquilibrium()** function in the msy class (msy.cpp).

Here is some output for the iterations:

In get_fmsy:
TOL = 0.0001, MAXITER = 300
fe =  0.293854 0.281872 0.0617747
m_f =  86.1943 60.9234 -7.88098
norm(m_f) = 105.845

fe =  0.420566 0.340488 0.0603322
m_f =  32.215 11.4237 -36.3962
norm(m_f) = 49.9299

fe =  0.423209 0.242645 0.057197
m_f =  21.703 2.82433 -37.6172
norm(m_f) = 43.5207

fe =  0.491036 0.218992 0.0549261
m_f =  24.099 4.57118 -38.4902
norm(m_f) = 45.6415

fe =  0.523826 0.14755 0.0521425
m_f =  20.821 1.89063 -39.0306
norm(m_f) = 44.2773

fe =  0.577168 0.097505 0.0496464
m_f =  20.7804 1.72273 -39.8439
norm(m_f) = 44.9703

fe =  0.624043 0.0343409 0.0470249
m_f =  19.1217 0.309641 -40.4811
norm(m_f) = 44.7712

fe =  0.676627 0.0342803 0.0444662
m_f =  18.1368 -0.591769 -41.2336
norm(m_f) = 45.05

fe =  0.70203 0.0341776 0.0413162
m_f =  15.6749 -2.4958 -41.1244
norm(m_f) = 44.0812

fe =  0.721953 0.0340612 0.0378646
m_f =  14.6143 -3.29701 -41.0138
norm(m_f) = 43.6644

fe =  0.74317 0.0339389 0.0341713
m_f =  13.8329 -3.87938 -40.907
norm(m_f) = 43.3564

fe =  0.7676 0.0338118 0.0302076
m_f =  13.0519 -4.45221 -40.767
norm(m_f) = 43.0363

fe =  0.796627 0.0336798 0.0259114
m_f =  12.2149 -5.05381 -40.5729
norm(m_f) = 42.6721

fe =  0.832182 0.0335427 0.0211884
m_f =  11.3001 -5.69494 -40.3023
norm(m_f) = 42.2421

fe =  0.877498 0.0334004 0.0158925
m_f =  10.2855 -6.38295 -39.9211
norm(m_f) = 41.716

fe =  0.938623 0.0332536 0.00977901
m_f =  9.1407 -7.12498 -39.3724
norm(m_f) = 41.0427

fe =  1.02855 0.0331062 0.00239028
m_f =  7.81931 -7.92592 -38.5515
norm(m_f) = 40.1271

fe =  1.18177 0.0329735 -0.0072914
m_f =  6.24714 -8.77741 -37.242
norm(m_f) = 38.769

fe =  1.53038 0.0329337 -0.0223105
m_f =  4.30262 -9.60609 -34.9161
norm(m_f) = 36.4681

fe =  3.19802 0.895801 -0.0597882
m_f =  1.82996 -9.97632 -29.9508
norm(m_f) = 31.6216

fe =  3.69748 1.22358 -2.33996
m_f =  -0.200904 -5.70167 -13.6883
norm(m_f) = 14.8297

fe =  15.8657 8.97348 -3.27223
m_f =  -0.513041 -5.14231 -11.822
norm(m_f) = 12.9022

fe =  -15.8831 -12.8543 -60.4323
m_f =  -0.929065 -1.42043 -2.13871
norm(m_f) = 2.73036

Error in matrix inverse -- matrix singular in inv(dmatrix)
Error in matrix inverse -- matrix singular in inv(dmatrix)
Error in matrix inverse -- matrix singular in inv(dmatrix)
fe =  nan nan nan
m_f =  1.02372e+213 1.02372e+213 1.02372e+213
norm(m_f) = inf

Error in matrix inverse -- matrix singular in inv(dmatrix)
Error in matrix inverse -- matrix singular in inv(dmatrix)
Error in matrix inverse -- matrix singular in inv(dmatrix)
fe =  nan nan nan
m_f =  nan nan nan
norm(m_f) = nan

**Comment by jaclyncleary** [comment]
can we comment out the calc get_fmsy() function? obviously not a permanent solution but perhaps a stop-gap that may allow us to continue with the bridging analysis.

**Comment by Shawkshaw** [comment]
It looks like this is what was done before. 
From the .tpl file:
"Aug 11, 2012. For the Pacific herring branch omit the get_fmsy calculations and use only the 
Bo calculation for the reference points.  As there are no MSY based reference
points required for the decision table."

**Comment by jaclyncleary** [comment]
yes, familiar stop-gap... would certainly prefer actual resolution (fingers-crossed)

**Comment by cgrandin** [comment]
How about we add a new toggle option in the control file for the fmsy calculations? I can get this going pretty quickly I think, and we wouldn't have to be modifying code for each stock, just control file settings.

**Comment by cgrandin** [comment]
Fixed the problem in commit 597a56653301db6daa7c4fdc1141003f6a0a41d8

Add this line to the misc controls section in the control file:
 0          # 17 -toggle to do the fmsy calculations (set to 0 for herring)

The hessian is still non-positive definite but I'll open a new issue for that.
