### ISSUE TITLE
projection_model

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/gfiscam#23]
I'm trying to track the calcs for column 2 in iscammcmc_proj_Gear1.csv, which is output from projection_model(tac(ii)) 

Where are the column headers assigned in this csv file? (ie, there are no variables called 04B0, 03B0 etc in iscam tpl)

**Comment by Shawkshaw** [comment]
column headers are set here:    
src/libs/utilities.cpp

**Comment by cgrandin** [comment]
I have traced this. It is the p_bt array in iscam which is the projected spawning biomass with average recruitment included. I didn't change the output column names because there is so much code that relies on it. We could do that, but we would have to run all the models again. That's another reason it was left because we always remember this after we have run all the models and it's too much work at the time... :(
