### ISSUE TITLE
Non-positive definite hessian for herring SOG when maturity vector is used

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/gfiscam#5]
This occurs when this maturity vector is used in the data file:
.24974 .9 1 1 1 1 1 1 1
**BUT this one works!**:
.25 .9 1 1 1 1 1 1 1

**Comment by Shawkshaw** [comment]
I did some more sensitivity analysis on the first value to test if it is the significant figures causing the issue (on both PC and Mac):
0.9-converges
0.5-converges
0.3-converges
0.29-DOes not converge
0.28-converges
0.2497-Does not converge
0.249-Does not converge
0.24-converges
0.2-converges
0.16-Does not converge
0.15-Does not converge
0.14-converges
0.1-converges
0.05-converges

**Comment by robynforrest** [comment]
Resolved. Problem was due to estimation of variance parameters. Resolved by fixing rho and vartheta at 2016 values. More testing needed of model sensitivity to these parameters. Also fixed apparent bug in iscam.tpl at L309-310.

t1 = sage;  (changed from t1 = 0;)
t2 = nage;  (changed from t2 = 0;)

Setting them to zero means that init_vector d_maturityVector(t1,t2) cannot be read in at L313
